name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'otra-rama-si-es-necesario'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build application
        run: |
          # Comandos para construir tu aplicaci칩n
          npm install
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build-directory
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run security check
        run: npm audit
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: npm run lint
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run static analysis
        run: npm run static-analysis
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./path-to-download-directory
      - name: Deploy to server
        run: |
          # Comandos para desplegar tu aplicaci칩n
          scp -r ./path-to-download-directory user@yourserver.com:/path/to/deploy
  verify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verify deployment
        run: |
          # Comandos para verificar que la aplicaci칩n est치 funcionando
          curl -f http://yourserver.com/path/to/your/application || exit 1


